# Generated by Django 4.1.2 on 2022-11-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_total_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
    ]
